name: Docker build base

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build docker --file Dockerfile --tag fossdevops/php-doctrine-rest-react:$(date +%s)
